# EDA IMDB

## 1.Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from datetime import datetime

## 2.Exploration par dataset


Exploration des 5 fichiers IMDB retenus. Pour chaque dataset : structure, valeurs manquantes, observations et décisions de preprocessing.

### 2.1 name.basics (people)


Contient les informations sur les personnes (acteurs, réalisateurs, etc.)  
**15 182 692 lignes — 6 colonnes**

| Colonne | % NaN | Décision |
|---------|-------|----------|
| nconst | 0% | Conserver (clé de jointure) |
| primaryName | 0.05% | Conserver |
| birthYear | 95.6% | **Supprimer** |
| deathYear | 98.3% | **Supprimer** |
| primaryProfession | 20% | Conserver |
| knownForTitles | 11.9% | Conserver |

In [4]:
people = pd.read_csv('name.basics.tsv', sep='\t',na_values='\\N')


#display(people.head())
print('People:', people.shape)
print(people[people.isna().any(axis=1)])
#print(people.isna().sum())
#print(people.isna().mean() * 100)

People: (15208735, 6)
             nconst          primaryName  birthYear  deathYear  \
46        nm0000047         Sophia Loren     1934.0        NaN
82        nm0000083          Alan Miller        NaN        NaN
83        nm0000084              Gong Li     1965.0        NaN
86        nm0000087       Elena Koreneva     1953.0        NaN
89        nm0000090  Armin Mueller-Stahl     1930.0        NaN
...             ...                  ...        ...        ...
15208730  nm9993714    Romeo del Rosario        NaN        NaN
15208731  nm9993716        Essias Loberg        NaN        NaN
15208732  nm9993717   Harikrishnan Rajan        NaN        NaN
15208733  nm9993718          Aayush Nair        NaN        NaN
15208734  nm9993719           Andre Hill        NaN        NaN

                            primaryProfession  \
46           actress,miscellaneous,soundtrack
82                     editor,writer,director
83             actress,producer,miscellaneous
86                    actress,director,writer
89               actor,miscellaneous,director
...                                       ...
15208730  animation_department,art_department
15208731                                  NaN
15208732                      cinematographer
15208733                      cinematographer
15208734                                  NaN

                                    knownForTitles
46         tt0060121,tt0054749,tt0058335,tt0076085
82        tt0424773,tt0969216,tt27504185,tt5969604
83         tt0473444,tt0397535,tt0101640,tt4566758
86         tt0122969,tt5847740,tt7529350,tt0080912
89         tt0765443,tt0117631,tt0963178,tt0139809
...                                            ...
15208730           tt11657662,tt14069590,tt2455546
15208731                                       NaN
15208732                                 tt8736744
15208733                                 tt8736744
15208734                                       NaN

[15002947 rows x 6 columns]

### 2.2 title.basics (titre)

Contient les informations de base sur les titres (films, séries, etc.)  
**12 388 768 lignes — 9 colonnes**

| Colonne | % NaN | Décision |
|---------|-------|----------|
| tconst | 0% | Conserver (jointure) |
| titleType | 0% | Conserver — filtre sur 'movie' |
| primaryTitle | 0.02% | Conserver |
| originalTitle | 0.02% | Conserver |
| isAdult | 0% | Conserver |
| startYear | 11.8% | Conserver |
| endYear | 98.8% | **Supprimer** |
| runtimeMinutes | 64% | Conserver |
| genres | 4.3% | Conserver |

In [3]:

titre = pd.read_csv('title.basics.tsv', sep='\t' ,na_values='\\N')


#display(titre.head())
print('Title', titre.shape)

#print(titre.isna().sum())
#print(titre.isna().mean() * 100)
#print(titre.info())
#print(titre.describe())

C:\Users\Jack\AppData\Local\Temp\ipykernel_15428\1548392702.py:1: DtypeWarning: Columns (0: runtimeMinutes) have mixed types. Specify dtype option on import or set low_memory=False.
  titre = pd.read_csv('title.basics.tsv', sep='\t' ,na_values='\\N')

Title (12404723, 9)

### 2.3 title.crew (Crew)

Contient les réalisateurs et scénaristes par titre.  
**12 388 768 lignes — 3 colonnes**

| Colonne | % NaN | Observation |
|---------|-------|-------------|
| tconst | 0% | jointure |
| directors | 44% | NaN élevé |
| writers | 49% | NaN élevé |

À décider : supprimer les colonnes directors/writers (44-49% NaN) ou supprimer entièrement title.crew au profit de title.principals qui couvre les mêmes infos avec 0% NaN.

In [9]:
Crews = pd.read_csv('title.crew.tsv', sep='\t',na_values='\\N')

display(Crews.head())
print(Crews.shape)
#print(Crews.isna().sum())
#print(Crews.info())
#print(Crews.describe())
print(Crews.isna().mean() * 100)

      tconst  directors    writers
0  tt0000001  nm0005690        NaN
1  tt0000002  nm0721526        NaN
2  tt0000003  nm0721526  nm0721526
3  tt0000004  nm0721526        NaN
4  tt0000005  nm0005690        NaN

(12388768, 3)
tconst        0.000000
directors    44.060362
writers      49.023938
dtype: float64

### 2.4 title.principals (Principal)

Table de liaison entre titres et personnes. Contient tous les rôles (acteur, réalisateur, producteur, etc.)  
**98 579 770 lignes — 3 colonnes**

| Colonne | % NaN | Décision |
|---------|-------|----------|
| tconst | 0% | Conserver (jointure) |
| nconst | 0% | Conserver (jointure) |
| category | 0% | Conserver |

0% de NaN sur 98M de lignes. Remplace title.crew.

In [10]:
Principal = pd.read_csv('title.principals.tsv', sep='\t', na_values='\\N', usecols=['tconst', 'nconst', 'category'])
display(Principal.head())
print(Principal.shape)
#print(Principal.isna().sum())
#print(Principal.info())
#print(Principal.describe())
print(Principal.isna().mean() * 100)

      tconst     nconst         category
0  tt0000001  nm1588970             self
1  tt0000001  nm0005690         director
2  tt0000001  nm0005690         producer
3  tt0000001  nm0374658  cinematographer
4  tt0000002  nm0721526         director

(98579770, 3)
tconst      0.0
nconst      0.0
category    0.0
dtype: float64

### 2.5 title.ratings (Ratings)

Contient les notes moyennes et le nombre de votes par titre.  
**1 652 901 lignes — 3 colonnes**

| Colonne | % NaN | Décision |
|---------|-------|----------|
| tconst | 0% | Conserver (jointure) |
| averageRating | 0% | Conserver |
| numVotes | 0% | Conserver |

Variable cible. 0% de NaN.

In [11]:
Ratings = pd.read_csv('title.ratings.tsv', sep='\t',na_values='\\N')

display(Ratings.head())
print(Ratings.shape)
#print(Ratings.isna().sum())
#print(Ratings.info())
#print(Ratings.describe())
print(Ratings.isna().mean() * 100)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2200
1  tt0000002            5.5       312
2  tt0000003            6.4      2311
3  tt0000004            5.1       196
4  tt0000005            6.2      3038

(1652901, 3)
tconst           0.0
averageRating    0.0
numVotes         0.0
dtype: float64