1. Import

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from datetime import datetime
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
df = pd.read_csv(r"G:\Recommandation-de-films\notebooks\02-preprocessing\movies_preprocessed_clean.csv")

On importe le documents et verifie les colonnes

In [43]:
df.shape

(330702, 33)

Je crée une variable qui va contenir uniquement les categories

In [44]:
col_genre = df.columns[df.columns.get_loc('Action'):]

Je crée une fonction de reco avec ma cosine_similarity pour une approche Content Based pour commencer 

A laquelle je rajoute un tri par weight_rating pour une meilleur precision

In [45]:


def recommandation(id_film, top_n=10):
    vecteur = df[col_genre].loc[id_film].values.reshape(1, -1)

    sims = cosine_similarity(vecteur, df[col_genre])[0]

    df_temp = df.copy()

    df_temp['sim'] = sims

    df_temp = df_temp.drop(id_film)
    
    return df_temp.sort_values(by=['sim', 'weight_rating'], ascending=[False, False]).head(top_n)

In [49]:
display(recommandation(65456))

,primaryTitle,startYear,runtimeMinutes,averageRating,numVotes,weight_rating,Action,Adult,Adventure,Animation,...,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western,sim
89094,Snatch,2000.0,102.0,8.2,974670.0,8.187111,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
64246,The Big Lebowski,1998.0,117.0,8.1,914984.0,8.086947,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
65451,"Lock, Stock and Two Smoking Barrels",1998.0,107.0,8.1,649072.0,8.081650,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
17616,Kind Hearts and Coronets,1949.0,106.0,8.0,41945.0,7.763051,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
52705,The Naked Gun: From the Files of Police Squad!,1988.0,85.0,7.6,221390.0,7.560761,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
57738,My Cousin Vinny,1992.0,120.0,7.6,157789.0,7.545542,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
52382,A Fish Called Wanda,1988.0,108.0,7.5,165180.0,7.451502,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
55972,Delicatessen,1991.0,99.0,7.5,94172.0,7.417187,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
22262,The Ladykillers,1955.0,91.0,7.6,34076.0,7.378217,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
25133,Big Deal on Madonna Street,1958.0,106.0,7.9,12762.0,7.330804,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0

Le systeme fonctionne bien , on a bien le top weight_rating en fonction du type de film rechercher ,pour rendre ca plus pratique on va crée une fonction de recherche de films

In [7]:
'''def recherche_par_titre(titre, top_n=10):
    index = df[df['primaryTitle'] == titre].index[0]
    return recommandation(index, top_n)
'''

"def recherche_par_titre(titre, top_n=10):\n    index = df[df['primaryTitle'] == titre].index[0]\n    return recommandation(index, top_n)\n"

Le systeme fonctionne mais oblige a taper le titre exact, sinon erreur. 
J'ajoute une recherche partielle avec str.contains (insensible a la casse) et un test conditionnel pour gerer le cas ou aucun film ne correspond.

In [51]:
def recherche_par_titre(titre, top_n=10):

    index = df[df['primaryTitle'].str.contains(titre, case=False, na=False)] \
              .sort_values('weight_rating', ascending=False).index[0]
    
    vecteur = df[col_genre].loc[index].values.reshape(1, -1)

    sims = cosine_similarity(vecteur, df[col_genre])[0]

    df_temp = df.copy()

    df_temp['sim'] = sims
    
    return df_temp.sort_values(['sim', 'weight_rating'], ascending=False).head(top_n)

In [58]:
recherche_par_titre('matrix')

,primaryTitle,startYear,runtimeMinutes,averageRating,numVotes,weight_rating,Action,Adult,Adventure,Animation,...,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western,sim
69308,The Matrix,1999.0,136.0,8.7,2239074.0,8.692991,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
140215,The Avengers,2012.0,143.0,8.0,1553660.0,7.992688,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
265220,Captain America: Civil War,2016.0,147.0,7.8,923835.0,7.789068,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
166029,X-Men: First Class,2011.0,131.0,7.7,762655.0,7.687580,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
94024,The Matrix Reloaded,2003.0,138.0,7.2,668899.0,7.190439,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
162926,Iron Man 2,2010.0,124.0,6.9,934414.0,6.895111,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
142564,The Amazing Spider-Man,2012.0,136.0,6.9,762160.0,6.894015,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
95671,The Matrix Revolutions,2003.0,129.0,6.7,573998.0,6.694208,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
179698,The Wolverine,2013.0,126.0,6.7,522901.0,6.693648,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0
132044,X-Men Origins: Wolverine,2009.0,107.0,6.5,566711.0,6.496294,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1.0

La recherche par titre marche niquel , on tape un film , trie par similarité + weight_rating