# Recommandation de films — Content-Based

## 1. Imports

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from datetime import datetime
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

## 2. Chargement des données

Import du dataset preprocessé et vérification des dimensions.

In [2]:
df = pd.read_csv(r"G:\Recommandation-de-films\notebooks\02-preprocessing\movies_preprocessed_clean.csv")

On importe le documents et verifie les colonnes

In [3]:
df.shape

(330702, 33)

Je crée une variable qui va contenir uniquement les categories

In [4]:
col_genre = df.columns[df.columns.get_loc('Action'):]

Je crée une fonction de reco avec ma cosine_similarity pour une approche Content Based pour commencer 

A laquelle je rajoute un tri par weight_rating pour une meilleur precision

In [5]:


def recommandation(id_film, top_n=10):
    vecteur = df[col_genre].loc[id_film].values.reshape(1, -1)

    sims = cosine_similarity(vecteur, df[col_genre])[0]

    df_temp = df.copy()

    df_temp['sim'] = sims

    df_temp = df_temp.drop(id_film)
    
    return df_temp.sort_values(by=['sim', 'weight_rating'], ascending=[False, False]).head(top_n)

In [6]:
display(recommandation(65456))

,primaryTitle,startYear,runtimeMinutes,averageRating,numVotes,weight_rating,Action,Adult,Adventure,Animation,...,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western,sim
89094,Snatch,2000.0,102.0,8.2,974670.0,8.187111,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
64246,The Big Lebowski,1998.0,117.0,8.1,914984.0,8.086947,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
65451,"Lock, Stock and Two Smoking Barrels",1998.0,107.0,8.1,649072.0,8.081650,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
17616,Kind Hearts and Coronets,1949.0,106.0,8.0,41945.0,7.763051,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
52705,The Naked Gun: From the Files of Police Squad!,1988.0,85.0,7.6,221390.0,7.560761,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
57738,My Cousin Vinny,1992.0,120.0,7.6,157789.0,7.545542,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
52382,A Fish Called Wanda,1988.0,108.0,7.5,165180.0,7.451502,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
55972,Delicatessen,1991.0,99.0,7.5,94172.0,7.417187,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
22262,The Ladykillers,1955.0,91.0,7.6,34076.0,7.378217,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0
25133,Big Deal on Madonna Street,1958.0,106.0,7.9,12762.0,7.330804,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.0

Le systeme fonctionne mais oblige a taper le titre exact, sinon erreur. 
J'ajoute une recherche partielle avec str.contains (insensible a la casse) et un test conditionnel pour gerer le cas ou aucun film ne correspond.

In [25]:
def recherche_par_titre(titre, top_n=10):

    index = df[df['primaryTitle'].str.contains(titre, case=False, na=False)] \
        .sort_values('weight_rating', ascending=False).index[0]
    features = list(col_genre) + ['year_scaled']

    vecteur = df[features].loc[index].values.reshape(1, -1)

    sims = cosine_similarity(vecteur, df[features])[0]

    df_temp = df.copy()
    
    df_temp['sim'] = sims
    
    return df_temp.sort_values(['sim', 'weight_rating'], ascending=False).head(top_n)

In [26]:
recherche_par_titre('godzilla')

,primaryTitle,startYear,runtimeMinutes,averageRating,numVotes,weight_rating,Action,Adult,Adventure,Animation,...,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western,year_scaled,sim
225816,Godzilla Minus One,2023.0,124.0,7.6,202364.0,7.557182,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
284028,Gran Turismo,2023.0,134.0,7.1,134361.0,7.058478,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
222224,Ponniyin Selvan: Part Two,2023.0,164.0,7.2,19779.0,6.951427,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
159841,The Creator,2023.0,133.0,6.7,196280.0,6.683401,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
148840,The Hunger Games: The Ballad of Songbirds & Sn...,2023.0,157.0,6.6,181306.0,6.585376,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
173610,The Wandering Earth II,2023.0,173.0,6.7,16345.0,6.550854,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
219233,Dovbush,2023.0,124.0,7.3,2723.0,6.506205,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
189438,Dasara,2023.0,156.0,6.6,12341.0,6.452021,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
169096,Concrete Utopia,2023.0,130.0,6.6,9130.0,6.421001,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0
309908,Creation of the Gods I: Kingdom of Storms,2023.0,148.0,6.6,6514.0,6.384135,1,0,1,0,...,0,0,0,0,0,0,0,0,0.977273,1.0

Résultats pertinents. On ajoute l'année au calcul de similarité pour affiner, au lieu de se baser sur les genres seuls.
On rempli les NA sur la mediane puis MinMaxScaler pour normaliser les années entre 0 et 1

In [10]:
df['startYear'] = df['startYear'].fillna(df['startYear'].median())
df['startYear'].isna().sum()

np.int64(0)

In [19]:
MMScaler = MinMaxScaler()
df['year_scaled'] = MMScaler.fit_transform(df[['startYear']])
df['year_scaled'].head()

0    0.000000
1    0.022727
2    0.090909
3    0.098485
4    0.098485
Name: year_scaled, dtype: float64

L'année nuance la similarité, mais son poids est trop faible par rapport aux colonnes genres.
On se retrouve avec un top 10 de mêmes genres que la recherche, mais cette fois-ci de la même année.